service: changes

provider:
  name: aws
  runtime: dotnetcore1.0

package:
  artifact: bin/release/netcoreapp1.0/deploy-package.zip
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  # list
  getChanges:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::GetChanges
    events:
      - http:
          method: get
          path: changes
          cors: true
          
  # create
  postChanges:
    handler: CsharpHandlers::AwsDotnetCsharp.Handler::PostChanges
    events:
      - http:
          method: post
          path: changes
          cors: true
          
custom:
  user: ${file(../serverless.yml):custom.user}
