service: changes

provider:
  name: aws
  runtime: dotnetcore2.0

package:
  artifact: src/bin/release/netcoreapp2.0/deploy-package.zip
#  exclude:
#    - exclude-me.js
#    - exclude-me-dir/**

functions:
  # list
  getChanges:
    handler: CsharpHandlers::changes.Handler::GetChanges
    events:
      - http:
          method: get
          path: changes
          cors: true

  # create
  postChanges:
    handler: CsharpHandlers::changes.Handler::PostChanges
    events:
      - http:
          method: post
          path: changes
          cors: true

  # put
  putChanges:
    handler: CsharpHandlers::changes.Handler::PutChange
    events:
      - http:
          method: put
          path: changes/{changeId}
          cors: true

  # delete
  deleteChanges:
    handler: CsharpHandlers::changes.Handler::DeleteChange
    events:
      - http:
          method: delete
          path: changes/{changeId}
          cors: true

custom:
  user: ${file(../serverless.yml):custom.user}
